name: 'AWS CodeGuru Security Action'
description: 'AWS CodeGuru Security Action'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  source_path:
    description: 'Path to source repository'
    default: .
    required: false
runs:
  using: docker
  image: docker://codeguru:latest
  args:
   - --source_path
   - ${{ inputs.source_path }}
